//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Instagram_Assistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FeedLikesTotalCount {
            get {
                return ((int)(this["FeedLikesTotalCount"]));
            }
            set {
                this["FeedLikesTotalCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LikeGoal {
            get {
                return ((int)(this["LikeGoal"]));
            }
            set {
                this["LikeGoal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UnfollowCount {
            get {
                return ((int)(this["UnfollowCount"]));
            }
            set {
                this["UnfollowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SkipChance {
            get {
                return ((int)(this["SkipChance"]));
            }
            set {
                this["SkipChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Activity {
            get {
                return ((int)(this["Activity"]));
            }
            set {
                this["Activity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RandomDelayValue {
            get {
                return ((int)(this["RandomDelayValue"]));
            }
            set {
                this["RandomDelayValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DelayValue {
            get {
                return ((int)(this["DelayValue"]));
            }
            set {
                this["DelayValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FeedStoriesTotalCount {
            get {
                return ((int)(this["FeedStoriesTotalCount"]));
            }
            set {
                this["FeedStoriesTotalCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int RestHoursFrom {
            get {
                return ((int)(this["RestHoursFrom"]));
            }
            set {
                this["RestHoursFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RestHoursTo {
            get {
                return ((int)(this["RestHoursTo"]));
            }
            set {
                this["RestHoursTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime RestDateFrom {
            get {
                return ((global::System.DateTime)(this["RestDateFrom"]));
            }
            set {
                this["RestDateFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime RestDateTo {
            get {
                return ((global::System.DateTime)(this["RestDateTo"]));
            }
            set {
                this["RestDateTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RandomStoriesDelay {
            get {
                return ((int)(this["RandomStoriesDelay"]));
            }
            set {
                this["RandomStoriesDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int StoriesDelay {
            get {
                return ((int)(this["StoriesDelay"]));
            }
            set {
                this["StoriesDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int StoriesSkipChance {
            get {
                return ((int)(this["StoriesSkipChance"]));
            }
            set {
                this["StoriesSkipChance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUnfollowIfFollowing {
            get {
                return ((bool)(this["IsUnfollowIfFollowing"]));
            }
            set {
                this["IsUnfollowIfFollowing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UnfollowDelay {
            get {
                return ((int)(this["UnfollowDelay"]));
            }
            set {
                this["UnfollowDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RandomUnfollowDelay {
            get {
                return ((int)(this["RandomUnfollowDelay"]));
            }
            set {
                this["RandomUnfollowDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsWorkTimeLimit {
            get {
                return ((bool)(this["IsWorkTimeLimit"]));
            }
            set {
                this["IsWorkTimeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RestTimeMinutes {
            get {
                return ((int)(this["RestTimeMinutes"]));
            }
            set {
                this["RestTimeMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxUnfollowPerHour {
            get {
                return ((int)(this["MaxUnfollowPerHour"]));
            }
            set {
                this["MaxUnfollowPerHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxStoriesPerHour {
            get {
                return ((int)(this["MaxStoriesPerHour"]));
            }
            set {
                this["MaxStoriesPerHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxLikePerHour {
            get {
                return ((int)(this["MaxLikePerHour"]));
            }
            set {
                this["MaxLikePerHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection AccountsRoles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AccountsRoles"]));
            }
            set {
                this["AccountsRoles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StopWordsPath {
            get {
                return ((string)(this["StopWordsPath"]));
            }
            set {
                this["StopWordsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoWordsPath {
            get {
                return ((string)(this["GoWordsPath"]));
            }
            set {
                this["GoWordsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WordsInNamePath {
            get {
                return ((string)(this["WordsInNamePath"]));
            }
            set {
                this["WordsInNamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFilteredAudiencePath {
            get {
                return ((string)(this["SaveFilteredAudiencePath"]));
            }
            set {
                this["SaveFilteredAudiencePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveAudiencePath {
            get {
                return ((string)(this["SaveAudiencePath"]));
            }
            set {
                this["SaveAudiencePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasBioParameter {
            get {
                return ((bool)(this["HasBioParameter"]));
            }
            set {
                this["HasBioParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasImageParameter {
            get {
                return ((bool)(this["HasImageParameter"]));
            }
            set {
                this["HasImageParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasHLparameter {
            get {
                return ((bool)(this["HasHLparameter"]));
            }
            set {
                this["HasHLparameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ProfileCategoryParameter {
            get {
                return ((int)(this["ProfileCategoryParameter"]));
            }
            set {
                this["ProfileCategoryParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNameSave {
            get {
                return ((bool)(this["IsNameSave"]));
            }
            set {
                this["IsNameSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsIdSave {
            get {
                return ((bool)(this["IsIdSave"]));
            }
            set {
                this["IsIdSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsPhoneSave {
            get {
                return ((bool)(this["IsPhoneSave"]));
            }
            set {
                this["IsPhoneSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsEmailSave {
            get {
                return ((bool)(this["IsEmailSave"]));
            }
            set {
                this["IsEmailSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinFollowersCount {
            get {
                return ((int)(this["MinFollowersCount"]));
            }
            set {
                this["MinFollowersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MinMediaCount {
            get {
                return ((int)(this["MinMediaCount"]));
            }
            set {
                this["MinMediaCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AccountTypeFilter {
            get {
                return ((int)(this["AccountTypeFilter"]));
            }
            set {
                this["AccountTypeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountCategoriesFilter {
            get {
                return ((string)(this["AccountCategoriesFilter"]));
            }
            set {
                this["AccountCategoriesFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HashatagTotalLikeCount {
            get {
                return ((int)(this["HashatagTotalLikeCount"]));
            }
            set {
                this["HashatagTotalLikeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GeoTotalLikeCount {
            get {
                return ((int)(this["GeoTotalLikeCount"]));
            }
            set {
                this["GeoTotalLikeCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HashtagTotatStoriesCount {
            get {
                return ((int)(this["HashtagTotatStoriesCount"]));
            }
            set {
                this["HashtagTotatStoriesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GeoTotalStoriesCount {
            get {
                return ((int)(this["GeoTotalStoriesCount"]));
            }
            set {
                this["GeoTotalStoriesCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ActionsPerTechAccountLimit {
            get {
                return ((int)(this["ActionsPerTechAccountLimit"]));
            }
            set {
                this["ActionsPerTechAccountLimit"] = value;
            }
        }
    }
}
